@startuml
actor       admin  as person
boundary    "密码修改界面" as secretboundary
control     "密码修改控制器" as secretcontrol
database    "用户表"    as userdata

person -> secretboundary : 打开密码修改界面
person -> secretcontrol : 修改自身密码申请
secretcontrol -> userdata : 修改密码
secretcontrol --> secretboundary :修改成功
person -> secretcontrol :重置用户密码申请
secretcontrol -> userdata : 查询用户是否存在
group 重置成功
    userdata --> secretcontrol : 用户名存在
    secretcontrol --> secretboundary :重置成功
end
group 重置失败
    userdata --> secretcontrol : 用户名不存在
    secretcontrol --> secretboundary :重置失败
end
@enduml